version : 3.9
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_new
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wpdatabase
    volumes:
      - wordpress_data:/var/www/html
volumes:
  wordpress_data:

